openapi: 3.0.0
info:
  title: Insta Chat
  description: API documentation for Insta Chat
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
paths:
  /applications:
    get:
      summary: Get all applications
      responses:
        '200':
          description: List of applications
          content:
            application/json:
              schema:
                type: object
                properties:
                  applications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Application'
    post:
      summary: Create a new application
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  application:
                    $ref: '#/components/schemas/Application'
        '422':
          $ref: '#/components/responses/BadRequest'
  /applications/{app_token}:
    put:
      summary: Update an application
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  application:
                    $ref: '#/components/schemas/Application'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/BadRequest'
  /applications/{app_token}/chats:
    get:
      summary: Get a list of chats
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
          description: App token
        - in: query
          name: page_token
          schema:
            type: integer
          description: Page token
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit
      responses:
        '200':
          description: List of chats
          content:
            application/json:
              schema:
                type: object
                properties:
                  chats:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chat'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create a chat
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  application:
                    $ref: '#/components/schemas/Chat'
        '400':
          $ref: '#/components/responses/BadRequest'
  /applications/{app_token}/chats/{chat_num}:  
    put:
      summary: Update a chat
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
        - in: path
          name: chat_num
          required: true
          schema:
            type: integer
          description: Chat number
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  chat:
                    $ref: '#/components/schemas/Chat'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
  /applications/{app_token}/chats/{chat_num}/messages:
    get:
      summary: Get all messages
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
          description: App token
        - in: path
          name: chat_num
          required: true
          schema:
            type: integer
          description: Chat number
        - in: query
          name: page_token
          schema:
            type: string
          description: Page token
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create a message
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
        - in: path
          name: chat_num
          required: true
          schema:
            type: integer
          description: Chat number
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                content:
                  type: string
                messaged_by:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/BadRequest'    
  /applications/{app_token}/chats/{chat_num}/messages/{message_num}:    
    put:
      summary: Update a message
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
        - in: path
          name: chat_num
          required: true
          schema:
            type: integer
          description: Chat number
        - in: path
          name: message_num
          required: true
          schema:
            type: integer
          description: Message number
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: Success
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
  /applications/{app_token}/chats/{chat_num}/messages/search:
    get:
      summary: Search messages
      parameters:
        - in: path
          name: app_token
          required: true
          schema:
            type: string
          description: App token
        - in: path
          name: chat_num
          required: true
          schema:
            type: integer
          description: Chat number
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: Search query
        - in: query
          name: sort_by
          schema:
            type: string
          description: Sort by
        - in: query
          name: page
          schema:
            type: integer
          description: Page
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/BadRequest'
    
components:
  schemas:
    Application:
      type: object
      properties:
        app_token:
          type: string
        name:
          type: string
        chats_count:
          type: integer
          default: 0
      required:
        - app_token
        - name
    Chat:
      type: object
      properties:
        chat_num:
          type: integer
        name:
          type: string
        messages_count:
          type: integer
          default: 0
      required:
        - chat_num
        - name  
    Message:
      type: object
      properties:
        message_num:
          type: integer
        messaged_at:
          type: string
          format: date-time
        content:
          type: string
        messaged_by:
          type: string
      required:
        - message_num
        - messaged_at
        - messaged_by  
  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    NotFound:
      description: Application not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    UnprocessableEntity:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
