port: 8080
app_tokens_key: "app_tokens"

endpoints:
  create_chat:
    queue: "kafka"
    topic: "chats"
    partition_key: "app_token"
  create_message:
    queue: "kafka"
    topic: "messages"
    partition_key: "app_token"

kafka:
  broker: "0.0.0.0:9092"

redis:
  host: "localhost"
  port: 6379
  namespace: "insta_chat"
  db: 0
